version: 2

sources:
models:
    - name: green_tripdata_full
      tags: ["Source"]
      description: "Source table for this project"
      columns:
          - name: tripID
            tests:
                - unique
                - not_null
          - name: vendorID
            tests:
                - not_null
          - name: RatecodeID
            tests:
                - not_null
          - name: PULocationID
            tests:
                - not_null
          - name: DOLocationID
            tests:
                - not_null

      schema: ny_green_taxi

      # loaded_at_field: record_loaded_at
      tables:
        - name: tripdata_2021_01
          identifier: tripdata_2021_01
        - name: tripdata_2021_02
          identifier: tripdata_2021_02
        - name: tripdata_2021_03
          identifier: tripdata_2021_03
         # freshness:
           # error_after: {count: 6, period: hour}
