version: 2

sources:
    - name: ny_green_taxi

      schema: ny_green_taxi

      # loaded_at_field: record_loaded_at
      tables:
        - name: tripdata_2021_01
          identifier: tripdata_2021_01
        - name: tripdata_2021_02
          identifier: tripdata_2021_02
        - name: tripdata_2021_03
          identifier: tripdata_2021_03
         # freshness:
           # error_after: {count: 6, period: hour}
